//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacts.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnIdIsVisible {
            get {
                return ((bool)(this["ColumnIdIsVisible"]));
            }
            set {
                this["ColumnIdIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnLastNameIsVisible {
            get {
                return ((bool)(this["ColumnLastNameIsVisible"]));
            }
            set {
                this["ColumnLastNameIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnFirstNameIsVisible {
            get {
                return ((bool)(this["ColumnFirstNameIsVisible"]));
            }
            set {
                this["ColumnFirstNameIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnPatronymicIsVisible {
            get {
                return ((bool)(this["ColumnPatronymicIsVisible"]));
            }
            set {
                this["ColumnPatronymicIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColumnDisplayNameIsVisible {
            get {
                return ((bool)(this["ColumnDisplayNameIsVisible"]));
            }
            set {
                this["ColumnDisplayNameIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColumnDepartmentIsVisible {
            get {
                return ((bool)(this["ColumnDepartmentIsVisible"]));
            }
            set {
                this["ColumnDepartmentIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnPositionIsVisible {
            get {
                return ((bool)(this["ColumnPositionIsVisible"]));
            }
            set {
                this["ColumnPositionIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ColumnCabinetIsVisible {
            get {
                return ((bool)(this["ColumnCabinetIsVisible"]));
            }
            set {
                this["ColumnCabinetIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColumnCommentsIsVisible {
            get {
                return ((bool)(this["ColumnCommentsIsVisible"]));
            }
            set {
                this["ColumnCommentsIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GroupContactsSelectedItem {
            get {
                return ((string)(this["GroupContactsSelectedItem"]));
            }
            set {
                this["GroupContactsSelectedItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColumnIdDisplayIndex {
            get {
                return ((int)(this["ColumnIdDisplayIndex"]));
            }
            set {
                this["ColumnIdDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ColumnLastNameDisplayIndex {
            get {
                return ((int)(this["ColumnLastNameDisplayIndex"]));
            }
            set {
                this["ColumnLastNameDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ColumnFirstNameDisplayIndex {
            get {
                return ((int)(this["ColumnFirstNameDisplayIndex"]));
            }
            set {
                this["ColumnFirstNameDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ColumnPatronymicDisplayIndex {
            get {
                return ((int)(this["ColumnPatronymicDisplayIndex"]));
            }
            set {
                this["ColumnPatronymicDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ColumnDisplayNameDisplayIndex {
            get {
                return ((int)(this["ColumnDisplayNameDisplayIndex"]));
            }
            set {
                this["ColumnDisplayNameDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ColumnDepartmentDisplayIndex {
            get {
                return ((int)(this["ColumnDepartmentDisplayIndex"]));
            }
            set {
                this["ColumnDepartmentDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int ColumnPositionDisplayIndex {
            get {
                return ((int)(this["ColumnPositionDisplayIndex"]));
            }
            set {
                this["ColumnPositionDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ColumnCabinetDisplayIndex {
            get {
                return ((int)(this["ColumnCabinetDisplayIndex"]));
            }
            set {
                this["ColumnCabinetDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ColumnCommentsDisplayIndex {
            get {
                return ((int)(this["ColumnCommentsDisplayIndex"]));
            }
            set {
                this["ColumnCommentsDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double Column0Width {
            get {
                return ((double)(this["Column0Width"]));
            }
            set {
                this["Column0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double Column1Width {
            get {
                return ((double)(this["Column1Width"]));
            }
            set {
                this["Column1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double Column2Width {
            get {
                return ((double)(this["Column2Width"]));
            }
            set {
                this["Column2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double Column3Width {
            get {
                return ((double)(this["Column3Width"]));
            }
            set {
                this["Column3Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double Column4Width {
            get {
                return ((double)(this["Column4Width"]));
            }
            set {
                this["Column4Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double Column5Width {
            get {
                return ((double)(this["Column5Width"]));
            }
            set {
                this["Column5Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double Column6Width {
            get {
                return ((double)(this["Column6Width"]));
            }
            set {
                this["Column6Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Column7Width {
            get {
                return ((double)(this["Column7Width"]));
            }
            set {
                this["Column7Width"] = value;
            }
        }
    }
}
